replicaCount: 1

image:
  repository: kira002/flask-app-example
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: cluster-reader
  annotations: {}
  clusterRoleBinding:
    create: true
    roleName: cluster-reader
    roleNamespace: ""

service:
  type: NodePort
  port: 8000
  nodePort: 30000

ingress:
  enabled: true                   
  hosts: 
    - "formazionesou.local"              
  annotations:
    kubernetes.io/ingress.class: nginx
    
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 5
