replicaCount: 1

image:
  repository: kira002/flask-app-example
  tag: "develop"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: false # Cambia a true se vuoi abilitare l'Ingress
  annotations: {} # Aggiungi annotazioni come richiesto dal tuo Ingress Controller
  hosts:
    - host: example.com # Cambia con il tuo dominio o IP
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [] 

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

