replicaCount: 1

image:
  repository: kira002/flask-app-example
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 32000

ingress:
  enabled: true
  className: nginx
  host: flask-app.local
  path: /
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
