replicaCount: 1

image:
  repository: kira002/flask-app-example
  tag: "develop"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: cluster-reader
  annotations: {}
  clusterRoleBinding:
    create: true
    roleName: cluster-reader
    roleNamespace: ""

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30000

ingress:
  enabled: true        # Abilitato per il Bonus Track
  className: "nginx"   # Nginx Ingress Controller
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: "/"  # Rewrite per il path root
  hosts:
    - host: formazionesou.local    # Dominio per l'accesso al servizio
      paths:
        - path: /
          pathType: Prefix         # Indica il tipo di percorso
        - path: /api
          pathType: Prefix         # Indica il tipo di percorso  
  tls: []  
    
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 5
