# values.yaml

image:
  repository: kira002/flask-app-example
  tag: "develop"  # Impostato a "latest" per default, ma sarà possibile cambiarlo

service:
  name: flask-app
  type: ClusterIP
  port: 80
